In [2]:
import numpy as np
np.random.seed(0)

# Working with Numpy ndarrays

## Creating 1D ndarrays

In [3]:
arr1D = np.array([1.1, 2.2, 3.3, 4.4, 5.5])
arr1D

array([1.1, 2.2, 3.3, 4.4, 5.5])

In [3]:
type(arr1D)

numpy.ndarray

## Creating 2D ndarrays

In [6]:
arr2D = np.array([[1, 2], [3, 4]])
arr2D

array([[1, 2],
       [3, 4]])

## Creating any dimension ndarrays

In [9]:
arr4D = np.array(range(16)).reshape((2, 2, 2, 2))
arr4D

array([[[[ 0,  1],
         [ 2,  3]],

        [[ 4,  5],
         [ 6,  7]]],


       [[[ 8,  9],
         [10, 11]],

        [[12, 13],
         [14, 15]]]])

In [5]:
arr1D.shape

(5,)

In [7]:
arr2D.shape

(2, 2)

In [10]:
arr4D.shape

(2, 2, 2, 2)

## numpy.zeros(...)

In [11]:
np.zeros(shape=(2,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

## numpy.ones(...)

In [12]:
np.ones(shape=(2,2))

array([[1., 1.],
       [1., 1.]])

## numpy.identity(...)

In [11]:
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

## numpy.arange(...)

In [15]:
np.arange(5)

array([0, 1, 2, 3, 4])

## numpy.random.randn(…)

In [14]:
np.random.randn(2,2)

array([[1.76405235, 0.40015721],
       [0.97873798, 2.2408932 ]])

# Data types used with Numpy ndarrays

## Creation of numpy.float64 array

In [16]:
np.array([-1, 0, 1], dtype=np.float64)

array([-1.,  0.,  1.])

## Creation of numpy.bool array

In [18]:
np.array([-1, 0, 1], dtype=bool)

array([ True, False,  True])

## ndarrays' dtype attribute

In [19]:
arr1D.dtype

dtype('float64')

## Conversion of underlying types of ndarray with numpy.ndarrays.astype(...)

In [17]:
arr1D.astype(np.int64).dtype

dtype('int64')

In [20]:
arr1D.astype(np.int64)

array([1, 2, 3, 4, 5])

# Indexing and slicing in Numpy arrays

## Direct Access to an ndarray's Element

In [21]:
arr = np.random.randn(3,3)
arr

array([[ 1.86755799, -0.97727788,  0.95008842],
       [-0.15135721, -0.10321885,  0.4105985 ],
       [ 0.14404357,  1.45427351,  0.76103773]])

In [22]:
arr[0]

array([ 1.86755799, -0.97727788,  0.95008842])

In [23]:
arr[0][1]

-0.977277879876411

In [24]:
arr[0, 1]

-0.977277879876411

In [25]:
arr[-1]

array([0.14404357, 1.45427351, 0.76103773])

## ndarray's Slicing

In [26]:
arr[1:]

array([[-0.15135721, -0.10321885,  0.4105985 ],
       [ 0.14404357,  1.45427351,  0.76103773]])

### Accessing all ndarray elements after the first one

In [27]:
arr[1:, :2]

array([[-0.15135721, -0.10321885],
       [ 0.14404357,  1.45427351]])

### Fetching all rows starting from teh 2nd and columns 1 and 2

In [28]:
arr[1:2, -2:-1]

array([[-0.10321885]])

### Slicing with no indices

In [29]:
arr[:][2]

array([0.14404357, 1.45427351, 0.76103773])

In [30]:
arr[:][:]

array([[ 1.86755799, -0.97727788,  0.95008842],
       [-0.15135721, -0.10321885,  0.4105985 ],
       [ 0.14404357,  1.45427351,  0.76103773]])

### Setting values of a slice to zero

In [31]:
arr1 = arr[1:2]
arr1

array([[-0.15135721, -0.10321885,  0.4105985 ]])

In [32]:
arr1[:] = 0
arr1

array([[0., 0., 0.]])

In [33]:
arr

array([[ 1.86755799, -0.97727788,  0.95008842],
       [ 0.        ,  0.        ,  0.        ],
       [ 0.14404357,  1.45427351,  0.76103773]])

In [34]:
arr_copy = arr.copy()

In [35]:
arr_copy[1:2] = 1
arr_copy

array([[ 1.86755799, -0.97727788,  0.95008842],
       [ 1.        ,  1.        ,  1.        ],
       [ 0.14404357,  1.45427351,  0.76103773]])

In [36]:
arr

array([[ 1.86755799, -0.97727788,  0.95008842],
       [ 0.        ,  0.        ,  0.        ],
       [ 0.14404357,  1.45427351,  0.76103773]])

In [37]:
arr[:] = np.nan
arr

array([[nan, nan, nan],
       [nan, nan, nan],
       [nan, nan, nan]])

## Boolean Indexing

In [46]:
arr = np.random.randn(3,3)
arr

array([[ 0.12167502,  0.44386323,  0.33367433],
       [ 1.49407907, -0.20515826,  0.3130677 ],
       [-0.85409574, -2.55298982,  0.6536186 ]])

In [40]:
arr < 0

array([[False, False, False],
       [False, False, False],
       [False, False, False]])

In [41]:
arr[(arr < 0)]

array([], dtype=float64)

In [42]:
(arr > -1) & (arr < 1)

array([[False, False, False],
       [False, False, False],
       [False, False, False]])

In [43]:
arr[((arr > -1) & (arr < 1))]

array([], dtype=float64)

In [44]:
arr[(arr < -1) | (arr > 1)]

array([], dtype=float64)

## Indexing with arrays

In [47]:
arr

array([[ 0.12167502,  0.44386323,  0.33367433],
       [ 1.49407907, -0.20515826,  0.3130677 ],
       [-0.85409574, -2.55298982,  0.6536186 ]])

In [48]:
arr[[0, 2]]

array([[ 0.12167502,  0.44386323,  0.33367433],
       [-0.85409574, -2.55298982,  0.6536186 ]])

In [49]:
arr[[0, 2], [1]]

array([ 0.44386323, -2.55298982])

In [50]:
arr[[2, 0]]

array([[-0.85409574, -2.55298982,  0.6536186 ],
       [ 0.12167502,  0.44386323,  0.33367433]])

# Basic ndarray operations with Numpy Universal Functions

In [51]:
arr2D

array([[1, 2],
       [3, 4]])

## Scalar multiplication with an ndarray

In [52]:
arr2D * 4

array([[ 4,  8],
       [12, 16]])

## Linear Combinations of ndarrays

In [53]:
2*arr2D + 3*arr2D

array([[ 5, 10],
       [15, 20]])

## Exponentiation of ndarrays

In [54]:
arr2D ** 2

array([[ 1,  4],
       [ 9, 16]])

## Addition of an ndarray with a scalar

In [55]:
arr2D + 10

array([[11, 12],
       [13, 14]])

## Transposing a matrix

In [51]:
arr2D.transpose()

array([[1, 3],
       [2, 4]])

## Changing layout of an ndarray

In [56]:
arr2D.reshape((4, 1))

array([[1],
       [2],
       [3],
       [4]])

In [57]:
arr = np.random.randn(9).reshape((3,3))
arr

array([[ 0.8644362 , -0.74216502,  2.26975462],
       [-1.45436567,  0.04575852, -0.18718385],
       [ 1.53277921,  1.46935877,  0.15494743]])

## Finding the minimum value in an ndarray

In [58]:
np.min(arr)

-1.4543656745987648

## Calculating the absolute value

In [59]:
np.abs(arr)

array([[0.8644362 , 0.74216502, 2.26975462],
       [1.45436567, 0.04575852, 0.18718385],
       [1.53277921, 1.46935877, 0.15494743]])

## Calculating the mean of an ndarray

In [60]:
np.mean(arr)

0.4392578005636864

In [61]:
np.mean(arr, axis=0)

array([0.31428325, 0.25765076, 0.7458394 ])

In [62]:
np.mean(arr, axis=1)

array([ 0.79734193, -0.53193034,  1.0523618 ])

## Finding the index of the maximum value in an ndarray

In [63]:
np.argmax(arr)

2

In [64]:
np.argmax(arr, axis=1)

array([2, 1, 0])

## Calculating the cumulative sum of elements of an ndarray

In [61]:
np.cumsum(arr)

array([0.8644362 , 0.12227118, 2.3920258 , 0.93766013, 0.98341865,
       0.7962348 , 2.32901401, 3.79837278, 3.95332021])

In [65]:
np.cumsum(arr, axis=1)

array([[ 0.8644362 ,  0.12227118,  2.3920258 ],
       [-1.45436567, -1.40860716, -1.59579101],
       [ 1.53277921,  3.00213798,  3.15708541]])

## Finding NaNs in an ndarray

In [66]:
arr[1, :] = np.nan
arr

array([[ 0.8644362 , -0.74216502,  2.26975462],
       [        nan,         nan,         nan],
       [ 1.53277921,  1.46935877,  0.15494743]])

In [64]:
np.isnan(arr)

array([[False, False, False],
       [ True,  True,  True],
       [False, False, False]])

## Finding the truth values of x1>x2 of two ndarrays

In [65]:
arr1 = np.random.randn(9).reshape((3,3))
arr1

array([[ 0.37816252, -0.88778575, -1.98079647],
       [-0.34791215,  0.15634897,  1.23029068],
       [ 1.20237985, -0.38732682, -0.30230275]])

In [66]:
arr2 = np.random.randn(9).reshape((3,3))
arr2

array([[-1.04855297, -1.42001794, -1.70627019],
       [ 1.9507754 , -0.50965218, -0.4380743 ],
       [-1.25279536,  0.77749036, -1.61389785]])

In [67]:
np.greater(arr1, arr2)

array([[ True,  True, False],
       [False,  True,  True],
       [ True, False,  True]])

In [68]:
arr1 > arr2

array([[ True,  True, False],
       [False,  True,  True],
       [ True, False,  True]])

## Boolean operations Any and All on ndarrays

In [69]:
arr_bool = (arr > -0.5) & (arr < 0.5)
arr_bool

array([[False, False, False],
       [False, False, False],
       [False, False,  True]])

In [70]:
arr_bool.any()

True

In [71]:
arr_bool.any(axis=1)

array([False, False,  True])

In [72]:
arr_bool.all()

False

In [73]:
arr_bool.all(axis=1)

array([False, False, False])

## Sorting ndarrays

In [74]:
arr1D = np.random.randn(10)
arr1D

array([-0.21274028, -0.89546656,  0.3869025 , -0.51080514, -1.18063218,
       -0.02818223,  0.42833187,  0.06651722,  0.3024719 , -0.63432209])

In [75]:
np.sort(arr1D)

array([-1.18063218, -0.89546656, -0.63432209, -0.51080514, -0.21274028,
       -0.02818223,  0.06651722,  0.3024719 ,  0.3869025 ,  0.42833187])

In [76]:
arr1D

array([-0.21274028, -0.89546656,  0.3869025 , -0.51080514, -1.18063218,
       -0.02818223,  0.42833187,  0.06651722,  0.3024719 , -0.63432209])

In [77]:
np.argsort(arr1D)

array([4, 1, 9, 3, 0, 5, 7, 8, 2, 6], dtype=int64)

In [78]:
arr1D.sort()
np.argsort(arr1D)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=int64)

## Searching within ndarrays

In [79]:
arr1 = np.array(range(1, 11))
arr1

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [80]:
arr2 = arr1 * 1000
arr2

array([ 1000,  2000,  3000,  4000,  5000,  6000,  7000,  8000,  9000,
       10000])

In [81]:
cond = np.random.randn(10) > 0
cond

array([False, False, False, False, False,  True, False, False,  True,
       False])

In [82]:
np.where(cond, arr1, arr2)

array([ 1000,  2000,  3000,  4000,  5000,     6,  7000,  8000,     9,
       10000])

# File operations on ndarrays

## File operations with Text files

In [67]:
arr

array([[ 0.8644362 , -0.74216502,  2.26975462],
       [        nan,         nan,         nan],
       [ 1.53277921,  1.46935877,  0.15494743]])

In [68]:
np.savetxt('arr.csv', arr, fmt='%0.2lf', delimiter=',')

In [69]:
%pycat arr.csv

In [70]:
arr_new = np.loadtxt('arr.csv', delimiter=',')
arr_new

array([[ 0.86, -0.74,  2.27],
       [  nan,   nan,   nan],
       [ 1.53,  1.47,  0.15]])

## File operations with Binary files

In [87]:
np.save('arr', arr)

In [88]:
arr_new = np.load('arr.npy')
arr_new

array([[ 0.8644362 , -0.74216502,  2.26975462],
       [        nan,         nan,         nan],
       [ 1.53277921,  1.46935877,  0.15494743]])

In [89]:
arr == arr_new

array([[ True,  True,  True],
       [False, False, False],
       [ True,  True,  True]])